// Use DBML to define your database structure
// Docs: https://dbml.dbdiagram.io/docs

Table "customers" {
  "id" INTEGER [pk, increment]
  "primary_address_id" INTEGER [unique]
  "preferred_payment_id" INTEGER
  "email_address" VARCHAR(320) [unique, not null]
  "password_hash" CHAR(60) [not null]
  "created_at" TIMESTAMPTZ [not null, default: `CURRENT_TIMESTAMP`]
}

Table "addresses" {
  "id" INTEGER [pk, increment]
  "country" VARCHAR(56) [not null]
  "administrative_division" VARCHAR(24)
  "city" VARCHAR(127) [not null]
  "line1" VARCHAR(127) [not null]
  "line2" VARCHAR(127)
  "postal_code" VARCHAR(10) [not null]
  "customer_id" INTEGER
}

Table "payment_methods" {
  "id" INTEGER [pk, increment]
  "card_number" VARCHAR(20) [not null]
  "card_expiration" DATE [not null]
  "card_code" SMALLINT [not null]
  "billing_address_id" INTEGER [not null]
  "customer_id" INTEGER [not null]
}

Table "products" {
  "id" INTEGER [pk, increment]
  "product_name" VARCHAR(50) [not null]
  "stock" INTEGER [not null]
  "seller_id" INTEGER [not null]
  "price" NUMERIC(10,2) [not null]
  "created_at" TIMESTAMPTZ [not null, default: `CURRENT_TIMESTAMP`]
}

Table "ratings" {
  "customer_id" INTEGER [not null]
  "product_id" INTEGER [not null]
  "rating" SMALLINT [not null, check: `rating > 0 AND rating <= 10`]
  "created_at" TIMESTAMPTZ [not null, default: `CURRENT_TIMESTAMP`]

  Indexes {
    (customer_id, product_id) [pk]
  }
}

Table "sellers" {
  "id" INTEGER [pk, increment]
  "seller_name" VARCHAR(63) [not null]
  "created_at" TIMESTAMPTZ [not null, default: `CURRENT_TIMESTAMP`]
}

Table "moderators" {
  "id" INTEGER [pk, increment]
  "created_at" TIMESTAMPTZ [not null, default: `CURRENT_TIMESTAMP`]
  "first_name" VARCHAR(20) [not null]
  "last_name" VARCHAR(30) [not null]
  "email_address" VARCHAR(255) [unique, not null]
  "password_hash" CHAR(60) [not null]
}

Table "reports" {
  "id" INTEGER [pk, increment]
  "customer_id" INTEGER [not null]
  "reviewed_by" INTEGER
  "reason" VARCHAR(60) [not null]
  "created_at" TIMESTAMPTZ [not null, default: `CURRENT_TIMESTAMP`]
}

Table "product_removals" {
  "removed_by" INTEGER [not null]
  "product_id" INTEGER [not null]
  "removed_at" TIMESTAMPTZ [not null, default: `CURRENT_TIMESTAMP`]

  Indexes {
    (product_id, removed_at) [pk]
  }
}

Table "seller_removals" {
  "removed_by" INTEGER [not null]
  "seller_id" INTEGER [not null]
  "removed_at" TIMESTAMPTZ [not null, default: `CURRENT_TIMESTAMP`]

  Indexes {
    (seller_id, removed_at) [pk]
  }
}

Table "purchases" {
  "id" INTEGER [pk, increment]
  "created_at" TIMESTAMPTZ [not null, default: `CURRENT_TIMESTAMP`]
  "customer_id" INTEGER [not null]
  "payment_method_id" INTEGER [not null]
}

Table "product_sales" {
  "id" INTEGER [pk, increment]
  "purchase_id" INTEGER [not null]
  "product_id" INTEGER [not null]
  "price_per_item" NUMERIC(10,2) [not null]
  "quantity" INTEGER [not null, default: 1]
}

Table "deliveries" {
  "id" INTEGER [pk, increment]
  "purchase_id" INTEGER [not null]
  "address_id" INTEGER [not null]
  "delivery_status" varchar(63) [default: 'processing']
  "shipped_on" DATE
  "estimated_delivery_time" TIMESTAMPTZ
}

// TODO: Go through these and verify that they are correct

Ref "fk_primary_address":"addresses"."id" < "customers"."primary_address_id"

Ref "fk_preferred_payment_id":"payment_methods"."id" < "customers"."preferred_payment_id"

Ref "fk_customer":"customers"."id" < "addresses"."customer_id"

Ref "fk_address":"addresses"."id" < "payment_methods"."billing_address_id"

Ref "fk_customer":"customers"."id" < "payment_methods"."customer_id"

Ref "fk_seller":"sellers"."id" < "products"."seller_id"

Ref "fk_customer":"customers"."id" < "ratings"."customer_id"

Ref "fk_product":"products"."id" < "ratings"."product_id"

Ref "fk_customer":"customers"."id" < "reports"."customer_id"

Ref "fk_moderator":"moderators"."id" < "reports"."reviewed_by"

Ref "fk_moderator":"moderators"."id" < "product_removals"."removed_by"

Ref "fk_product":"products"."id" < "product_removals"."product_id"

Ref "fk_moderator":"moderators"."id" < "seller_removals"."removed_by"

Ref "fk_seller":"sellers"."id" < "seller_removals"."seller_id"

Ref "fk_customer":"customers"."id" < "purchases"."customer_id"

Ref "fk_payment_method":"payment_methods"."id" < "purchases"."payment_method_id"

Ref "fk_purchase":"purchases"."id" < "product_sales"."purchase_id"

Ref "fk_product":"products"."id" < "product_sales"."product_id"

Ref "fk_purchase":"purchases"."id" < "deliveries"."purchase_id"

Ref "fk_address":"addresses"."id" <> "deliveries"."address_id"
